version: "3.8"

services:
  app:
    build: .
    container_name: users-cli
    depends_on:
      - mongodb
    environment:
      MONGODB_URI: mongodb://mongodb:27017/users-cli
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app
    command: ["sh", "-c", "while ! nc -z mongodb 27017; do sleep 1; done; node app.js"]

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: